"""empty message

Revision ID: 1358da91a8cd
Revises: 38dc550c12a8
Create Date: 2020-05-10 16:34:00.522065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1358da91a8cd'
down_revision = '38dc550c12a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=16), nullable=True),
    sa.Column('expired_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user', 'request_token', ['request_token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('request_token')
    # ### end Alembic commands ###
